### ISSUE TITLE
Not showing my ELA on the phone

### ISSUE THREAD

**Issue by Guiko** [cyber-republic/elastos-smartweb-alpha#1]
I installed trinity.epk and E2E.epk, works great.
I send 1 ELA to an E2E adress as a test

But it is not showing on my android phone
The 1 Ela is  https://blockchain.elastos.org/address/EX2Jy3CxR5ZLAtNJRHPwUck5CQydzvY7oU

Any idea?

**Comment by Guiko** [comment]
Ah I receive a sound signal from the phone, I think it's from Trinity, like 15min after sending the ela

**Comment by kpachhai** [comment]
This is an alpha version and even the wallet demo isn’t connected to the mainnet. Please refrain from using this demo app as an official elastos wallet because it’s not. It’s just a demo :)
