### ISSUE TITLE
How create  elastos dapps?

### ISSUE THREAD

**Issue by yunyouming** [cyber-republic/elastos-smartweb-alpha#4]
我看到了几个做好的 DAPP，能否举个创建DAPP的方法？怎么一步一步实现的。Thanks

**Comment by kpachhai** [comment]
You can check out the demo app code on this repository. The elastos dapp are all html5 apps and are developed using ionic/Cordova framework. There will be more demo apps and tutorials in the future.

**Comment by Arfanmi** [comment]
So going forward, on IOS, Windows and Mac/Ubuntu will these also be HTML5 DApps?

**Comment by kevingzhang** [comment]
We are working on React Native and other major frameworks (researching on Flutter/Dart). Native mobile apps are supported using SDK already.

So they do not have to be HTML app.
