### ISSUE TITLE
Cannot install trinity.apk

### ISSUE THREAD

**Issue by adrianR84** [cyber-republic/elastos-smartweb-alpha#5]
Hello
Cannot install the trinity app on android 6.0.1 after accepting the requirements.
What android version is required ?

**Comment by kpachhai** [comment]
What’s the error you’re getting?
-Kiran

**Comment by adrianR84** [comment]
it is just saying that the application was not installed....

**Comment by PatriotMinded** [comment]
I am getting file to big and parsing error on my andriod

**Comment by kpachhai** [comment]
U need android 7 or later. For some apps, u might even need 7.1.1 or later.
-Kiran

**Comment by 1683942030** [comment]
i tested ,the app is not be signed ,you must sign it  with android apktools

**Comment by kpachhai** [comment]
You can change the settings on your android phone to install unsigned apps. This is an alpha release so it's not really signed at this point. So, you will have to manually trust this application if you're to install it onto your phone.
